"""German interface strings."""
from __future__ import annotations


STRINGS: dict[str, str] = {
    "app.name": "CV Builder",
    "section.step": "Schritt {current} von {total}",
    "action.cancel": "Abbrechen",
    "action.done": "Fertig",

    "status.library": "Lokale Lebenslauf-Bibliothek",
    "status.saving": "Wird gespeichert…",
    "status.saved": "Gespeichert",
    "status.save_failed": "Speichern fehlgeschlagen",
    "status.exporting_pdf": "PDF wird exportiert…",
    "status.exported": "Exportiert · {name}",
    "status.pdf_failed": "PDF-Export fehlgeschlagen",
    "status.json_exported": "JSON exportiert",
    "status.progress": "{percent}% ausgefüllt",

    "library.subtitle": "Ihre Lebenslauf-Bibliothek",
    "library.eyebrow": "IHRE DOKUMENTE",
    "library.title": "Lebenslauf zum Fortfahren wählen",
    "library.import_json": "JSON importieren",
    "library.new_cv": "+  Neuer Lebenslauf",
    "library.settings": "Einstellungen",
    "library.empty_title": "Ersten Lebenslauf erstellen",
    "library.empty_subtitle": "Ihre Änderungen werden automatisch auf diesem Gerät gespeichert.",
    "library.empty_action": "+  Lebenslauf erstellen",
    "library.card_meta": "{person}  ·  {percent}% ausgefüllt",
    "library.card_updated": "Aktualisiert {date}",
    "library.recently_updated": "Kürzlich aktualisiert",
    "library.no_name": "Noch kein Name eingetragen",
    "library.preview_failed": "Dokument konnte nicht angezeigt werden",
    "library.action.open": "Öffnen",
    "library.action.pdf": "PDF",
    "library.action.rename": "Umbenennen",
    "library.action.duplicate": "Duplizieren",
    "library.action.delete": "Löschen",

    "editor.all_cvs": "Alle Lebensläufe",
    "editor.export_json": "JSON exportieren",
    "editor.export_pdf": "PDF exportieren",
    "editor.build_your_cv": "LEBENSLAUF ERSTELLEN",
    "editor.privacy": "Lokal und privat\nIhre Daten bleiben auf diesem Gerät.",
    "nav.profile": "1    Profil",
    "nav.summary": "2    Profiltext",
    "nav.experience": "3    Erfahrung",
    "nav.education": "4    Ausbildung",
    "nav.preview": "5    Vorschau",

    "profile.title": "Profil",
    "profile.subtitle": "Die wichtigsten Angaben im Kopf Ihres Lebenslaufs.",
    "profile.name": "Vollständiger Name",
    "profile.headline": "Berufsbezeichnung",
    "profile.location": "Ort",
    "profile.email": "E-Mail",
    "profile.linkedin": "LinkedIn oder Website",
    "profile.skills": "Kernkompetenzen",
    "profile.skills_hint": "Eine Kompetenz pro Zeile",
    "profile.languages": "Sprachen",
    "profile.languages_hint": "Eine Sprache pro Zeile",

    "summary.title": "Profiltext",
    "summary.subtitle": "Trennen Sie Absätze durch eine Leerzeile.",
    "summary.label": "Berufliches Profil",
    "summary.character_count": "Zeichen: {count}",

    "experience.title": "Berufserfahrung",
    "experience.subtitle": "Alle Positionen bei einem Arbeitgeber stehen unter einem Unternehmen.",
    "experience.add_action": "+  Unternehmen hinzufügen",
    "experience.add_title": "Unternehmen hinzufügen",
    "experience.edit_title": "Unternehmen bearbeiten",
    "experience.edit_subtitle": "Die Positionen bei diesem Arbeitgeber fügen Sie im nächsten Schritt hinzu.",
    "experience.company": "Unternehmen",
    "experience.role": "Position",
    "experience.place": "Ort",
    "experience.add_position": "+  Position hinzufügen",
    "experience.position_add_title": "Position hinzufügen",
    "experience.position_edit_title": "Position bearbeiten",
    "experience.position_subtitle": "Beschreiben Sie Position, Aufgaben und messbare Erfolge.",
    "experience.date_start": "Beginn",
    "experience.date_end": "Ende",
    "experience.current": "Ich arbeite aktuell hier",
    "experience.month": "Monat",
    "experience.year": "Jahr",
    "experience.no_positions": "Noch keine Positionen",
    "experience.save_position": "Position speichern",
    "experience.intro": "Beschreibung der Position oder des Projekts",
    "experience.work": "Hauptaufgaben",
    "experience.results": "Erfolge",
    "experience.line_hint": "Ein Punkt pro Zeile",
    "experience.save_entry": "Speichern",
    "experience.empty_title": "Noch keine Erfahrung hinzugefügt",
    "experience.empty_subtitle": "Fügen Sie ein Unternehmen hinzu und danach die dort gehaltenen Positionen.",
    "experience.empty_action": "+  Erstes Unternehmen hinzufügen",
    "experience.untitled_role": "Position ohne Titel",
    "experience.no_company": "Unternehmen nicht angegeben",
    "experience.action.edit": "Bearbeiten",
    "experience.action.delete": "Löschen",

    "education.title": "Ausbildung",
    "education.subtitle": "Fügen Sie den für diesen Lebenslauf passendsten Abschluss hinzu.",
    "education.action": "Vorschau  →",
    "education.institution": "Institution",
    "education.qualification": "Abschluss und Zeitraum",

    "preview.title": "Vorschau",
    "preview.subtitle": "Prüfen Sie jede Seite und legen Sie vor dem Export Sprache und Seitenleistenfarbe fest.",
    "preview.sidebar_colour": "FARBE DER SEITENLEISTE",
    "preview.cv_language": "SPRACHE DES LEBENSLAUFS",
    "preview.cv_language_hint": "Die Sprache der gedruckten Abschnittsüberschriften.",

    "theme.linkedin": "LinkedIn-Grau",
    "theme.olive-deep": "Dunkles Oliv",
    "theme.olive-soft": "Helles Oliv",
    "theme.forest": "Waldgrün",
    "theme.mint": "Mint",
    "theme.ink": "Tiefschwarz",
    "theme.midnight": "Mitternachtsblau",

    "settings.title": "Einstellungen",
    "settings.interface_language": "Sprache der Oberfläche",
    "settings.interface_hint": "Die Sprache dieser Anwendung. Jeder Lebenslauf hat seine eigene Sprache, die im Schritt „Vorschau“ gewählt wird.",
    "settings.example_json": "Beispiel-JSON",
    "settings.example_json_hint": "Das Importformat mit Beispieldaten. Geben Sie diese Datei zusammen mit Ihrem Werdegang an einen KI-Chat — er baut daraus einen fertigen Lebenslauf, den Sie hier wieder importieren, ganz ohne Abtippen.",
    "settings.example_json_save": "Beispiel-JSON speichern…",
    "settings.example_json_prompt_hint": "Ein Prompt zum Mitschicken:",
    "settings.example_json_prompt": "Im Anhang ist das JSON-Format der App CV Builder, gefüllt mit Beispieldaten. Darunter steht mein Werdegang. Erstelle eine einzige JSON-Datei mit exakt derselben Struktur, gefüllt mit meinen Daten. Behalte alle Schlüssel und Verschachtelungsebenen unverändert bei, füge keine Felder hinzu und benenne keine um, und schreibe den Inhalt in der Sprache meines Textes unten. Gib nur das JSON zurück, ohne Kommentar.",
    "settings.copy_prompt": "Prompt kopieren",
    "settings.prompt_copied": "Kopiert ✓",

    "dialog.rename.title": "Lebenslauf umbenennen",
    "dialog.rename.text": "Neuen Namen für diesen Lebenslauf eingeben:",
    "dialog.delete.title": "Lebenslauf löschen",
    "dialog.delete.message": "„{title}“ von diesem Gerät löschen?",
    "dialog.delete.detail": "Das lässt sich nicht rückgängig machen. Exportieren Sie zuerst das JSON, wenn Sie eine Sicherung brauchen.",
    "dialog.delete_entry.title": "Eintrag löschen",
    "dialog.delete_entry.message": "Dieses Unternehmen und alle zugehörigen Positionen löschen?",
    "dialog.select_entry.title": "Eintrag wählen",
    "dialog.select_entry.message": "Wählen Sie zuerst einen Erfahrungseintrag.",
    "dialog.missing_info.title": "Fehlende Angaben",
    "dialog.missing_info.message": "Der Name des Unternehmens ist erforderlich.",
    "dialog.delete_position.title": "Position löschen",
    "dialog.delete_position.message": "Diese Position löschen?",
    "dialog.missing_position.message": "Position und Beginn sind erforderlich.",
    "dialog.invalid_dates.title": "Zeitraum prüfen",
    "dialog.invalid_dates.message": "Das Enddatum darf nicht vor dem Startdatum liegen.",
    "dialog.missing_name.title": "Name fehlt",
    "dialog.missing_name.message": "Geben Sie einen Namen ein, bevor Sie das PDF erstellen.",
    "dialog.import.title": "Lebenslauf-JSON importieren",
    "dialog.export_json.title": "Lebenslauf als JSON exportieren",
    "dialog.example.title": "Beispiel-Lebenslauf als JSON speichern",
    "dialog.example_saved.title": "Beispiel-JSON gespeichert",
    "dialog.example_saved.message": "Bearbeiten Sie diese Datei und importieren Sie sie zurück in CV Builder:\n{path}",
    "dialog.export_pdf.title": "PDF exportieren",
    "dialog.pdf_created.title": "PDF erstellt",
    "dialog.pdf_created.message": "Ihr Lebenslauf wurde gespeichert unter:\n{path}",
    "error.library_open": "Lebenslauf-Bibliothek konnte nicht geöffnet werden",
    "error.create": "Lebenslauf konnte nicht erstellt werden",
    "error.open": "Lebenslauf konnte nicht geöffnet werden",
    "error.rename": "Lebenslauf konnte nicht umbenannt werden",
    "error.duplicate": "Lebenslauf konnte nicht dupliziert werden",
    "error.delete": "Lebenslauf konnte nicht gelöscht werden",
    "error.import": "JSON konnte nicht importiert werden",
    "error.export_json": "JSON konnte nicht exportiert werden",
    "error.example": "Beispiel-JSON konnte nicht gespeichert werden",
    "error.pdf": "PDF konnte nicht erstellt werden",

    "filetype.json": "CV Builder JSON",
    "filetype.pdf": "PDF-Dokument",
    "filetype.all": "Alle Dateien",
    "file.example_json": "cv-builder-example.json",
    "file.default_cv": "mein-lebenslauf",
    "file.pdf_name": "{name} - Lebenslauf.pdf",

    "placeholder.name": "IHR NAME",
    "placeholder.headline": "IHRE POSITION | IHRE SPEZIALISIERUNG | IHR MEHRWERT",
    "placeholder.location": "IHRE STADT, IHR LAND",
    "placeholder.email": "ihre.email@example.com",
    "placeholder.linkedin": "linkedin.com/in/ihr-profil",
    "placeholder.skills": "KOMPETENZ EINS\nKOMPETENZ ZWEI\nKOMPETENZ DREI",
    "placeholder.languages": "Englisch – C1\nSpanisch – B2",
    "placeholder.summary": (
        "Schreiben Sie eine kurze Einführung zu Ihrem beruflichen Hintergrund "
        "und Ihrer Kernkompetenz.\n\nBeschreiben Sie Teams, Projekte oder "
        "Produkte, mit denen Sie gearbeitet haben.\n\nHeben Sie Ihre "
        "wichtigsten Ergebnisse und Fachgebiete hervor."
    ),
    "placeholder.company": "AKTUELLES ODER LETZTES UNTERNEHMEN",
    "placeholder.role": "IHRE POSITION",
    "placeholder.place": "STADT, LAND",
    "placeholder.intro": "Beschreiben Sie Position oder Projekt in einem Satz.",
    "placeholder.work": "Beschreiben Sie eine zentrale Aufgabe.\nBeschreiben Sie einen weiteren Beitrag.",
    "placeholder.results": "Beschreiben Sie ein messbares Ergebnis oder eine Geschäftswirkung.",
    "placeholder.institution": "UNIVERSITÄT ODER SCHULE",
    "placeholder.qualification": "ABSCHLUSS ODER QUALIFIKATION (JAHR – JAHR)",
}
