"""English interface strings — the canonical key set every locale must match."""
from __future__ import annotations


STRINGS: dict[str, str] = {
    # --- shell -----------------------------------------------------------
    "app.name": "CV Builder",
    "section.step": "Section {current} of {total}",
    "action.cancel": "Cancel",
    "action.done": "Done",
    # --- status line -----------------------------------------------------
    "status.library": "Local CV library",
    "status.saving": "Saving…",
    "status.saved": "Saved",
    "status.save_failed": "Save failed",
    "status.exporting_pdf": "Exporting PDF…",
    "status.exported": "Exported · {name}",
    "status.pdf_failed": "PDF export failed",
    "status.json_exported": "JSON exported",
    "status.progress": "{percent}% complete",
    # --- library screen --------------------------------------------------
    "library.subtitle": "Your CV library",
    "library.eyebrow": "YOUR DOCUMENTS",
    "library.title": "Choose a CV to continue",
    "library.import_json": "Import JSON",
    "library.new_cv": "+  New CV",
    "library.settings": "Settings",
    "library.empty_title": "Create your first CV",
    "library.empty_subtitle": "Your changes will be saved automatically on this device.",
    "library.empty_action": "+  Create CV",
    "library.card_meta": "{person}  ·  {percent}% complete",
    "library.card_updated": "Updated {date}",
    "library.recently_updated": "Recently updated",
    "library.no_name": "No name added yet",
    "library.preview_failed": "Document could not be previewed",
    "library.action.open": "Open",
    "library.action.pdf": "PDF",
    "library.action.rename": "Rename",
    "library.action.duplicate": "Duplicate",
    "library.action.delete": "Delete",
    # --- editor shell ----------------------------------------------------
    "editor.all_cvs": "All CVs",
    "editor.export_json": "Export JSON",
    "editor.export_pdf": "Export PDF",
    "editor.build_your_cv": "BUILD YOUR CV",
    "editor.privacy": "Local and private\nYour data stays on this device.",
    "nav.profile": "1    Profile",
    "nav.summary": "2    Summary",
    "nav.experience": "3    Experience",
    "nav.education": "4    Education",
    "nav.preview": "5    Preview",
    # --- section 1: profile ----------------------------------------------
    "profile.title": "Profile",
    "profile.subtitle": "The essential details shown at the top of your CV.",
    "profile.name": "Full name",
    "profile.headline": "Professional headline",
    "profile.location": "Location",
    "profile.email": "Email",
    "profile.linkedin": "LinkedIn or website",
    "profile.skills": "Core skills",
    "profile.skills_hint": "One skill per line",
    # --- section 2: summary ----------------------------------------------
    "summary.title": "Summary",
    "summary.subtitle": "Use a blank line between paragraphs.",
    "summary.label": "Professional summary",
    "summary.character_count": "Characters: {count}",
    # --- section 3: experience -------------------------------------------
    "experience.title": "Experience",
    "experience.subtitle": "Put the most relevant role first.",
    "experience.add_action": "+  Add role",
    "experience.add_title": "Add experience",
    "experience.edit_title": "Edit experience",
    "experience.edit_subtitle": "Describe the role, responsibilities and measurable results.",
    "experience.company": "Company",
    "experience.role": "Role",
    "experience.dates": "Dates",
    "experience.duration": "Total duration",
    "experience.place": "Location",
    "experience.intro": "Role or project description",
    "experience.work": "Key responsibilities",
    "experience.results": "Results",
    "experience.line_hint": "One item per line",
    "experience.save_entry": "Save entry",
    "experience.empty_title": "No experience added yet",
    "experience.empty_subtitle": "Add a role to show your responsibilities and impact.",
    "experience.empty_action": "+  Add your first role",
    "experience.untitled_role": "Untitled role",
    "experience.no_company": "Company not specified",
    "experience.action.edit": "Edit",
    "experience.action.delete": "Delete",
    # --- section 4: education --------------------------------------------
    "education.title": "Education",
    "education.subtitle": "Add the qualification most relevant to this CV.",
    "education.action": "Preview  →",
    "education.institution": "Institution",
    "education.qualification": "Qualification and dates",
    # --- section 5: preview ----------------------------------------------
    "preview.title": "Preview",
    "preview.subtitle": "Check every page, then set the language and sidebar colour before exporting.",
    "preview.sidebar_colour": "SIDEBAR COLOUR",
    "preview.cv_language": "CV LANGUAGE",
    "preview.cv_language_hint": "The language of the printed section headings.",
    # --- sidebar themes --------------------------------------------------
    "theme.linkedin": "LinkedIn grey",
    "theme.olive-deep": "Deep olive",
    "theme.olive-soft": "Soft olive",
    "theme.forest": "Forest green",
    "theme.mint": "Mint",
    "theme.ink": "Ink black",
    "theme.midnight": "Midnight navy",
    # --- settings dialog -------------------------------------------------
    "settings.title": "Settings",
    "settings.interface_language": "Interface language",
    "settings.interface_hint": "The language of this application. Each CV carries its own language, chosen on the Preview step.",
    "settings.example_json": "Example JSON",
    "settings.example_json_hint": "The import format, filled in with sample data. Hand this file to any AI chat together with your work history and it can assemble a complete CV you import back here — no retyping.",
    "settings.example_json_save": "Save example JSON…",
    "settings.example_json_prompt_hint": "A prompt to send along with the file:",
    "settings.example_json_prompt": "Attached is the JSON format used by the CV Builder app, filled with sample data. Below is my work history. Build a single JSON file with exactly the same structure, filled in with my data. Keep every key and nesting level unchanged, do not add or rename fields, and write the content in the language I use below. Return only the JSON, with no commentary.",
    "settings.copy_prompt": "Copy prompt",
    "settings.prompt_copied": "Copied ✓",
    # --- dialogs and errors ----------------------------------------------
    "dialog.rename.title": "Rename CV",
    "dialog.rename.text": "Enter a new name for this CV:",
    "dialog.delete.title": "Delete CV",
    "dialog.delete.message": 'Delete "{title}" from this device?',
    "dialog.delete.detail": "This cannot be undone. Export its JSON first if you need a backup.",
    "dialog.delete_entry.title": "Delete entry",
    "dialog.delete_entry.message": "Delete this experience entry?",
    "dialog.select_entry.title": "Select an entry",
    "dialog.select_entry.message": "Select an experience entry first.",
    "dialog.missing_info.title": "Missing information",
    "dialog.missing_info.message": "Company and role are required.",
    "dialog.missing_name.title": "Missing name",
    "dialog.missing_name.message": "Enter a name before generating the PDF.",
    "dialog.import.title": "Import CV JSON",
    "dialog.export_json.title": "Export CV JSON",
    "dialog.example.title": "Save example CV JSON",
    "dialog.example_saved.title": "Example JSON saved",
    "dialog.example_saved.message": "Edit this file and import it back into CV Builder:\n{path}",
    "dialog.export_pdf.title": "Export PDF",
    "dialog.pdf_created.title": "PDF created",
    "dialog.pdf_created.message": "Your CV was saved to:\n{path}",
    "error.library_open": "Could not open CV library",
    "error.create": "Could not create CV",
    "error.open": "Could not open CV",
    "error.rename": "Could not rename CV",
    "error.duplicate": "Could not duplicate CV",
    "error.delete": "Could not delete CV",
    "error.import": "Could not import JSON",
    "error.export_json": "Could not export JSON",
    "error.example": "Could not save example JSON",
    "error.pdf": "Could not generate PDF",
    # --- file dialog vocabulary ------------------------------------------
    "filetype.json": "CV Builder JSON",
    "filetype.pdf": "PDF document",
    "filetype.all": "All files",
    "file.example_json": "cv-builder-example.json",
    "file.default_cv": "my-cv",
    "file.pdf_name": "{name} - CV.pdf",
    # --- placeholders ([PHD]: UI hints, never document data) --------------
    "placeholder.name": "YOUR NAME",
    "placeholder.headline": "YOUR JOB TITLE | YOUR SPECIALIZATION | YOUR KEY VALUE",
    "placeholder.location": "YOUR CITY, YOUR COUNTRY",
    "placeholder.email": "your.email@example.com",
    "placeholder.linkedin": "linkedin.com/in/your-profile",
    "placeholder.skills": "SKILL ONE\nSKILL TWO\nSKILL THREE",
    "placeholder.summary": (
        "Write a short introduction about your professional background and main "
        "expertise.\n\nDescribe the teams, projects, or products you have worked "
        "with.\n\nHighlight your most relevant results and areas of specialization."
    ),
    "placeholder.company": "CURRENT OR MOST RECENT COMPANY",
    "placeholder.duration": "X YEARS X MONTHS",
    "placeholder.role": "YOUR JOB TITLE",
    "placeholder.dates": "MONTH YEAR - PRESENT",
    "placeholder.place": "CITY, COUNTRY",
    "placeholder.intro": "Add a one-sentence role or project description.",
    "placeholder.work": "Describe a key responsibility.\nDescribe another contribution.",
    "placeholder.results": "Describe a measurable result or business impact.",
    "placeholder.institution": "UNIVERSITY OR SCHOOL NAME",
    "placeholder.qualification": "DEGREE OR QUALIFICATION (YEAR - YEAR)",
}
