"""Spanish interface strings."""
from __future__ import annotations


STRINGS: dict[str, str] = {
    "app.name": "CV Builder",
    "section.step": "Paso {current} de {total}",
    "action.cancel": "Cancelar",
    "action.done": "Listo",

    "status.library": "Biblioteca local de CV",
    "status.saving": "Guardando…",
    "status.saved": "Guardado",
    "status.save_failed": "No se pudo guardar",
    "status.exporting_pdf": "Exportando PDF…",
    "status.exported": "Exportado · {name}",
    "status.pdf_failed": "Falló la exportación a PDF",
    "status.json_exported": "JSON exportado",
    "status.progress": "{percent}% completado",

    "library.subtitle": "Tu biblioteca de CV",
    "library.eyebrow": "TUS DOCUMENTOS",
    "library.title": "Elige un CV para continuar",
    "library.import_json": "Importar JSON",
    "library.new_cv": "+  Nuevo CV",
    "library.settings": "Ajustes",
    "library.empty_title": "Crea tu primer CV",
    "library.empty_subtitle": "Tus cambios se guardarán automáticamente en este dispositivo.",
    "library.empty_action": "+  Crear CV",
    "library.card_meta": "{person}  ·  {percent}% completado",
    "library.card_updated": "Actualizado {date}",
    "library.recently_updated": "Actualizado hace poco",
    "library.no_name": "Aún sin nombre",
    "library.preview_failed": "No se pudo mostrar el documento",
    "library.action.open": "Abrir",
    "library.action.pdf": "PDF",
    "library.action.rename": "Renombrar",
    "library.action.duplicate": "Duplicar",
    "library.action.delete": "Eliminar",

    "editor.all_cvs": "Todos los CV",
    "editor.export_json": "Exportar JSON",
    "editor.export_pdf": "Exportar PDF",
    "editor.build_your_cv": "CREA TU CV",
    "editor.privacy": "Local y privado\nTus datos permanecen en este dispositivo.",
    "nav.profile": "1    Perfil",
    "nav.summary": "2    Resumen",
    "nav.experience": "3    Experiencia",
    "nav.education": "4    Formación",
    "nav.preview": "5    Vista previa",

    "profile.title": "Perfil",
    "profile.subtitle": "Los datos esenciales que aparecen al inicio de tu CV.",
    "profile.name": "Nombre completo",
    "profile.headline": "Titular profesional",
    "profile.location": "Ubicación",
    "profile.email": "Correo electrónico",
    "profile.linkedin": "LinkedIn o sitio web",
    "profile.skills": "Competencias clave",
    "profile.skills_hint": "Una competencia por línea",
    "profile.languages": "Idiomas",
    "profile.languages_hint": "Un idioma por línea",

    "summary.title": "Resumen",
    "summary.subtitle": "Separa los párrafos con una línea en blanco.",
    "summary.label": "Perfil profesional",
    "summary.character_count": "Caracteres: {count}",

    "experience.title": "Experiencia",
    "experience.subtitle": "Agrupa bajo una misma empresa todos los puestos que ocupaste allí.",
    "experience.add_action": "+  Añadir empresa",
    "experience.add_title": "Añadir empresa",
    "experience.edit_title": "Editar empresa",
    "experience.edit_subtitle": "Los puestos en esta empresa se añaden en la pantalla siguiente.",
    "experience.company": "Empresa",
    "experience.role": "Puesto",
    "experience.place": "Ubicación",
    "experience.add_position": "+  Añadir puesto",
    "experience.position_add_title": "Añadir puesto",
    "experience.position_edit_title": "Editar puesto",
    "experience.position_subtitle": "Describe el puesto, las responsabilidades y los logros medibles.",
    "experience.date_start": "Inicio",
    "experience.date_end": "Fin",
    "experience.current": "Trabajo aquí actualmente",
    "experience.month": "Mes",
    "experience.year": "Año",
    "experience.no_positions": "Aún no hay puestos",
    "experience.save_position": "Guardar puesto",
    "experience.intro": "Descripción del puesto o proyecto",
    "experience.work": "Responsabilidades principales",
    "experience.results": "Logros",
    "experience.line_hint": "Un elemento por línea",
    "experience.save_entry": "Guardar",
    "experience.empty_title": "Aún no hay experiencia",
    "experience.empty_subtitle": "Añade una empresa y después los puestos que ocupaste en ella.",
    "experience.empty_action": "+  Añadir tu primera empresa",
    "experience.untitled_role": "Puesto sin título",
    "experience.no_company": "Empresa no indicada",
    "experience.action.edit": "Editar",
    "experience.action.delete": "Eliminar",

    "education.title": "Formación",
    "education.subtitle": "Añade la titulación más relevante para este CV.",
    "education.action": "Vista previa  →",
    "education.institution": "Institución",
    "education.qualification": "Titulación y fechas",

    "preview.title": "Vista previa",
    "preview.subtitle": "Revisa cada página y elige el idioma y el color de la barra lateral antes de exportar.",
    "preview.sidebar_colour": "COLOR DE LA BARRA LATERAL",
    "preview.cv_language": "IDIOMA DEL CV",
    "preview.cv_language_hint": "El idioma de los títulos de sección impresos.",

    "theme.linkedin": "Gris LinkedIn",
    "theme.olive-deep": "Oliva oscuro",
    "theme.olive-soft": "Oliva claro",
    "theme.forest": "Verde bosque",
    "theme.mint": "Menta",
    "theme.ink": "Negro tinta",
    "theme.midnight": "Azul medianoche",

    "settings.title": "Ajustes",
    "settings.interface_language": "Idioma de la interfaz",
    "settings.interface_hint": "El idioma de esta aplicación. Cada CV tiene su propio idioma, que se elige en el paso «Vista previa».",
    "settings.example_json": "JSON de ejemplo",
    "settings.example_json_hint": "El formato de importación relleno con datos de muestra. Entrega este archivo a cualquier chat de IA junto con tu trayectoria laboral y podrá montar un CV completo que importas de vuelta aquí, sin teclear nada.",
    "settings.example_json_save": "Guardar JSON de ejemplo…",
    "settings.example_json_prompt_hint": "Un prompt para enviar junto al archivo:",
    "settings.example_json_prompt": "Adjunto el formato JSON que usa la aplicación CV Builder, relleno con datos de muestra. Abajo está mi trayectoria laboral. Crea un único archivo JSON con exactamente la misma estructura, relleno con mis datos. Mantén todas las claves y niveles de anidamiento sin cambios, no añadas ni renombres campos, y escribe el contenido en el idioma de mi texto de abajo. Devuelve solo el JSON, sin comentarios.",
    "settings.copy_prompt": "Copiar prompt",
    "settings.prompt_copied": "Copiado ✓",

    "dialog.rename.title": "Renombrar CV",
    "dialog.rename.text": "Introduce un nuevo nombre para este CV:",
    "dialog.delete.title": "Eliminar CV",
    "dialog.delete.message": "¿Eliminar «{title}» de este dispositivo?",
    "dialog.delete.detail": "Esto no se puede deshacer. Exporta antes su JSON si necesitas una copia de seguridad.",
    "dialog.delete_entry.title": "Eliminar entrada",
    "dialog.delete_entry.message": "¿Eliminar esta empresa y todos sus puestos?",
    "dialog.select_entry.title": "Selecciona una entrada",
    "dialog.select_entry.message": "Selecciona primero una entrada de experiencia.",
    "dialog.missing_info.title": "Faltan datos",
    "dialog.missing_info.message": "El nombre de la empresa es obligatorio.",
    "dialog.delete_position.title": "Eliminar puesto",
    "dialog.delete_position.message": "¿Eliminar este puesto?",
    "dialog.missing_position.message": "El puesto y la fecha de inicio son obligatorios.",
    "dialog.invalid_dates.title": "Revisa las fechas",
    "dialog.invalid_dates.message": "La fecha de fin no puede ser anterior a la de inicio.",
    "dialog.missing_name.title": "Falta el nombre",
    "dialog.missing_name.message": "Introduce un nombre antes de generar el PDF.",
    "dialog.import.title": "Importar CV desde JSON",
    "dialog.export_json.title": "Exportar CV a JSON",
    "dialog.example.title": "Guardar CV de ejemplo en JSON",
    "dialog.example_saved.title": "JSON de ejemplo guardado",
    "dialog.example_saved.message": "Edita este archivo e impórtalo de nuevo en CV Builder:\n{path}",
    "dialog.export_pdf.title": "Exportar PDF",
    "dialog.pdf_created.title": "PDF creado",
    "dialog.pdf_created.message": "Tu CV se guardó en:\n{path}",
    "error.library_open": "No se pudo abrir la biblioteca de CV",
    "error.create": "No se pudo crear el CV",
    "error.open": "No se pudo abrir el CV",
    "error.rename": "No se pudo renombrar el CV",
    "error.duplicate": "No se pudo duplicar el CV",
    "error.delete": "No se pudo eliminar el CV",
    "error.import": "No se pudo importar el JSON",
    "error.export_json": "No se pudo exportar el JSON",
    "error.example": "No se pudo guardar el JSON de ejemplo",
    "error.pdf": "No se pudo generar el PDF",

    "filetype.json": "CV Builder JSON",
    "filetype.pdf": "Documento PDF",
    "filetype.all": "Todos los archivos",
    "file.example_json": "cv-builder-example.json",
    "file.default_cv": "mi-cv",
    "file.pdf_name": "{name} - CV.pdf",

    "placeholder.name": "TU NOMBRE",
    "placeholder.headline": "TU PUESTO | TU ESPECIALIZACIÓN | TU VALOR CLAVE",
    "placeholder.location": "TU CIUDAD, TU PAÍS",
    "placeholder.email": "tu.correo@example.com",
    "placeholder.linkedin": "linkedin.com/in/tu-perfil",
    "placeholder.skills": "COMPETENCIA UNO\nCOMPETENCIA DOS\nCOMPETENCIA TRES",
    "placeholder.languages": "Inglés - C1\nEspañol - B2",
    "placeholder.summary": (
        "Escribe una breve introducción sobre tu trayectoria profesional y tu "
        "experiencia principal.\n\nDescribe los equipos, proyectos o productos "
        "con los que has trabajado.\n\nDestaca tus resultados más relevantes y "
        "tus áreas de especialización."
    ),
    "placeholder.company": "EMPRESA ACTUAL O MÁS RECIENTE",
    "placeholder.role": "TU PUESTO",
    "placeholder.place": "CIUDAD, PAÍS",
    "placeholder.intro": "Describe el puesto o proyecto en una frase.",
    "placeholder.work": "Describe una responsabilidad clave.\nDescribe otra contribución.",
    "placeholder.results": "Describe un resultado medible o su impacto en el negocio.",
    "placeholder.institution": "UNIVERSIDAD O CENTRO EDUCATIVO",
    "placeholder.qualification": "TITULACIÓN O CUALIFICACIÓN (AÑO - AÑO)",
}
