"""French interface strings."""
from __future__ import annotations


STRINGS: dict[str, str] = {
    "app.name": "CV Builder",
    "section.step": "Étape {current} sur {total}",
    "action.cancel": "Annuler",
    "action.done": "Terminé",

    "status.library": "Bibliothèque locale de CV",
    "status.saving": "Enregistrement…",
    "status.saved": "Enregistré",
    "status.save_failed": "Échec de l’enregistrement",
    "status.exporting_pdf": "Export PDF…",
    "status.exported": "Exporté · {name}",
    "status.pdf_failed": "Échec de l’export PDF",
    "status.json_exported": "JSON exporté",
    "status.progress": "{percent}% complété",

    "library.subtitle": "Votre bibliothèque de CV",
    "library.eyebrow": "VOS DOCUMENTS",
    "library.title": "Choisissez un CV pour continuer",
    "library.import_json": "Importer un JSON",
    "library.new_cv": "+  Nouveau CV",
    "library.settings": "Réglages",
    "library.empty_title": "Créez votre premier CV",
    "library.empty_subtitle": "Vos modifications seront enregistrées automatiquement sur cet appareil.",
    "library.empty_action": "+  Créer un CV",
    "library.card_meta": "{person}  ·  {percent}% complété",
    "library.card_updated": "Mis à jour {date}",
    "library.recently_updated": "Mis à jour récemment",
    "library.no_name": "Aucun nom saisi",
    "library.preview_failed": "Impossible d’afficher le document",
    "library.action.open": "Ouvrir",
    "library.action.pdf": "PDF",
    "library.action.rename": "Renommer",
    "library.action.duplicate": "Dupliquer",
    "library.action.delete": "Supprimer",

    "editor.all_cvs": "Tous les CV",
    "editor.export_json": "Exporter le JSON",
    "editor.export_pdf": "Exporter le PDF",
    "editor.build_your_cv": "CRÉEZ VOTRE CV",
    "editor.privacy": "Local et privé\nVos données restent sur cet appareil.",
    "nav.profile": "1    Profil",
    "nav.summary": "2    Résumé",
    "nav.experience": "3    Expérience",
    "nav.education": "4    Formation",
    "nav.preview": "5    Aperçu",

    "profile.title": "Profil",
    "profile.subtitle": "Les informations essentielles affichées en haut de votre CV.",
    "profile.name": "Nom complet",
    "profile.headline": "Intitulé professionnel",
    "profile.location": "Localisation",
    "profile.email": "E-mail",
    "profile.linkedin": "LinkedIn ou site web",
    "profile.skills": "Compétences clés",
    "profile.skills_hint": "Une compétence par ligne",
    "profile.languages": "Langues",
    "profile.languages_hint": "Une langue par ligne",

    "summary.title": "Résumé",
    "summary.subtitle": "Séparez les paragraphes par une ligne vide.",
    "summary.label": "Profil professionnel",
    "summary.character_count": "Caractères : {count}",

    "experience.title": "Expérience",
    "experience.subtitle": "Regroupez sous une même entreprise tous les postes que vous y avez occupés.",
    "experience.add_action": "+  Ajouter une entreprise",
    "experience.add_title": "Ajouter une entreprise",
    "experience.edit_title": "Modifier l’entreprise",
    "experience.edit_subtitle": "Les postes occupés dans cette entreprise s’ajoutent à l’étape suivante.",
    "experience.company": "Entreprise",
    "experience.role": "Poste",
    "experience.place": "Localisation",
    "experience.add_position": "+  Ajouter un poste",
    "experience.position_add_title": "Ajouter un poste",
    "experience.position_edit_title": "Modifier le poste",
    "experience.position_subtitle": "Décrivez le poste, les responsabilités et les résultats mesurables.",
    "experience.date_start": "Début",
    "experience.date_end": "Fin",
    "experience.current": "J’y travaille actuellement",
    "experience.month": "Mois",
    "experience.year": "Année",
    "experience.no_positions": "Aucun poste pour l’instant",
    "experience.save_position": "Enregistrer le poste",
    "experience.intro": "Description du poste ou du projet",
    "experience.work": "Responsabilités principales",
    "experience.results": "Réalisations",
    "experience.line_hint": "Un élément par ligne",
    "experience.save_entry": "Enregistrer",
    "experience.empty_title": "Aucune expérience ajoutée",
    "experience.empty_subtitle": "Ajoutez une entreprise, puis les postes que vous y avez occupés.",
    "experience.empty_action": "+  Ajouter votre première entreprise",
    "experience.untitled_role": "Poste sans intitulé",
    "experience.no_company": "Entreprise non précisée",
    "experience.action.edit": "Modifier",
    "experience.action.delete": "Supprimer",

    "education.title": "Formation",
    "education.subtitle": "Ajoutez le diplôme le plus pertinent pour ce CV.",
    "education.action": "Aperçu  →",
    "education.institution": "Établissement",
    "education.qualification": "Diplôme et période",

    "preview.title": "Aperçu",
    "preview.subtitle": "Vérifiez chaque page, puis choisissez la langue et la couleur de la barre latérale avant d’exporter.",
    "preview.sidebar_colour": "COULEUR DE LA BARRE LATÉRALE",
    "preview.cv_language": "LANGUE DU CV",
    "preview.cv_language_hint": "La langue des titres de section imprimés.",

    "theme.linkedin": "Gris LinkedIn",
    "theme.olive-deep": "Olive foncé",
    "theme.olive-soft": "Olive clair",
    "theme.forest": "Vert forêt",
    "theme.mint": "Menthe",
    "theme.ink": "Noir encre",
    "theme.midnight": "Bleu nuit",

    "settings.title": "Réglages",
    "settings.interface_language": "Langue de l’interface",
    "settings.interface_hint": "La langue de cette application. Chaque CV possède sa propre langue, choisie à l’étape « Aperçu ».",
    "settings.example_json": "JSON d’exemple",
    "settings.example_json_hint": "Le format d’import rempli avec des données d’exemple. Confiez ce fichier à n’importe quel chat IA avec votre parcours professionnel : il en tirera un CV complet que vous réimportez ici, sans rien retaper.",
    "settings.example_json_save": "Enregistrer le JSON d’exemple…",
    "settings.example_json_prompt_hint": "Un prompt à envoyer avec le fichier :",
    "settings.example_json_prompt": "Ci-joint le format JSON utilisé par l’application CV Builder, rempli avec des données d’exemple. Ci-dessous, mon parcours professionnel. Construis un seul fichier JSON ayant exactement la même structure, rempli avec mes données. Conserve toutes les clés et tous les niveaux d’imbrication à l’identique, n’ajoute ni ne renomme aucun champ, et rédige le contenu dans la langue de mon texte ci-dessous. Ne renvoie que le JSON, sans commentaire.",
    "settings.copy_prompt": "Copier le prompt",
    "settings.prompt_copied": "Copié ✓",

    "dialog.rename.title": "Renommer le CV",
    "dialog.rename.text": "Saisissez un nouveau nom pour ce CV :",
    "dialog.delete.title": "Supprimer le CV",
    "dialog.delete.message": "Supprimer « {title} » de cet appareil ?",
    "dialog.delete.detail": "Cette action est irréversible. Exportez d’abord son JSON si vous voulez une sauvegarde.",
    "dialog.delete_entry.title": "Supprimer l’entrée",
    "dialog.delete_entry.message": "Supprimer cette entreprise et tous ses postes ?",
    "dialog.select_entry.title": "Sélectionnez une entrée",
    "dialog.select_entry.message": "Sélectionnez d’abord une expérience.",
    "dialog.missing_info.title": "Informations manquantes",
    "dialog.missing_info.message": "Le nom de l’entreprise est obligatoire.",
    "dialog.delete_position.title": "Supprimer le poste",
    "dialog.delete_position.message": "Supprimer ce poste ?",
    "dialog.missing_position.message": "Le poste et la date de début sont obligatoires.",
    "dialog.invalid_dates.title": "Vérifiez les dates",
    "dialog.invalid_dates.message": "La date de fin ne peut pas précéder la date de début.",
    "dialog.missing_name.title": "Nom manquant",
    "dialog.missing_name.message": "Saisissez un nom avant de générer le PDF.",
    "dialog.import.title": "Importer un CV au format JSON",
    "dialog.export_json.title": "Exporter le CV au format JSON",
    "dialog.example.title": "Enregistrer un CV d’exemple en JSON",
    "dialog.example_saved.title": "JSON d’exemple enregistré",
    "dialog.example_saved.message": "Modifiez ce fichier puis réimportez-le dans CV Builder :\n{path}",
    "dialog.export_pdf.title": "Exporter le PDF",
    "dialog.pdf_created.title": "PDF créé",
    "dialog.pdf_created.message": "Votre CV a été enregistré dans :\n{path}",
    "error.library_open": "Impossible d’ouvrir la bibliothèque de CV",
    "error.create": "Impossible de créer le CV",
    "error.open": "Impossible d’ouvrir le CV",
    "error.rename": "Impossible de renommer le CV",
    "error.duplicate": "Impossible de dupliquer le CV",
    "error.delete": "Impossible de supprimer le CV",
    "error.import": "Impossible d’importer le JSON",
    "error.export_json": "Impossible d’exporter le JSON",
    "error.example": "Impossible d’enregistrer le JSON d’exemple",
    "error.pdf": "Impossible de générer le PDF",

    "filetype.json": "CV Builder JSON",
    "filetype.pdf": "Document PDF",
    "filetype.all": "Tous les fichiers",
    "file.example_json": "cv-builder-example.json",
    "file.default_cv": "mon-cv",
    "file.pdf_name": "{name} - CV.pdf",

    "placeholder.name": "VOTRE NOM",
    "placeholder.headline": "VOTRE POSTE | VOTRE SPÉCIALISATION | VOTRE VALEUR CLÉ",
    "placeholder.location": "VOTRE VILLE, VOTRE PAYS",
    "placeholder.email": "votre.email@example.com",
    "placeholder.linkedin": "linkedin.com/in/votre-profil",
    "placeholder.skills": "COMPÉTENCE UN\nCOMPÉTENCE DEUX\nCOMPÉTENCE TROIS",
    "placeholder.languages": "Anglais - C1\nEspagnol - B2",
    "placeholder.summary": (
        "Rédigez une courte introduction sur votre parcours professionnel et "
        "votre expertise principale.\n\nDécrivez les équipes, projets ou "
        "produits sur lesquels vous avez travaillé.\n\nMettez en avant vos "
        "résultats les plus pertinents et vos domaines de spécialisation."
    ),
    "placeholder.company": "ENTREPRISE ACTUELLE OU LA PLUS RÉCENTE",
    "placeholder.role": "VOTRE POSTE",
    "placeholder.place": "VILLE, PAYS",
    "placeholder.intro": "Décrivez le poste ou le projet en une phrase.",
    "placeholder.work": "Décrivez une responsabilité clé.\nDécrivez une autre contribution.",
    "placeholder.results": "Décrivez un résultat mesurable ou un impact sur l’activité.",
    "placeholder.institution": "UNIVERSITÉ OU ÉTABLISSEMENT",
    "placeholder.qualification": "DIPLÔME OU QUALIFICATION (ANNÉE - ANNÉE)",
}
