"""Japanese interface strings."""
from __future__ import annotations


STRINGS: dict[str, str] = {
    "app.name": "CV Builder",
    "section.step": "ステップ {current} / {total}",
    "action.cancel": "キャンセル",
    "action.done": "完了",

    "status.library": "ローカル履歴書ライブラリ",
    "status.saving": "保存中…",
    "status.saved": "保存しました",
    "status.save_failed": "保存できませんでした",
    "status.exporting_pdf": "PDF を書き出し中…",
    "status.exported": "書き出し完了 · {name}",
    "status.pdf_failed": "PDF の書き出しに失敗しました",
    "status.json_exported": "JSON を書き出しました",
    "status.progress": "{percent}% 完成",

    "library.subtitle": "履歴書ライブラリ",
    "library.eyebrow": "ドキュメント",
    "library.title": "続ける履歴書を選択",
    "library.import_json": "JSON を読み込む",
    "library.new_cv": "+  新しい履歴書",
    "library.settings": "設定",
    "library.empty_title": "最初の履歴書を作成",
    "library.empty_subtitle": "変更はこの端末に自動保存されます。",
    "library.empty_action": "+  履歴書を作成",
    "library.card_meta": "{person}  ·  {percent}% 完成",
    "library.card_updated": "更新 {date}",
    "library.recently_updated": "最近更新",
    "library.no_name": "氏名が未入力です",
    "library.preview_failed": "ドキュメントを表示できませんでした",
    "library.action.open": "開く",
    "library.action.pdf": "PDF",
    "library.action.rename": "名前を変更",
    "library.action.duplicate": "複製",
    "library.action.delete": "削除",

    "editor.all_cvs": "すべての履歴書",
    "editor.export_json": "JSON を書き出す",
    "editor.export_pdf": "PDF を書き出す",
    "editor.build_your_cv": "履歴書を作成",
    # Kept short: the editor sidebar wraps at 174px and Japanese breaks by
    # character, so a longer line leaves an orphan on the last row.
    "editor.privacy": "ローカル・プライベート\nデータは端末内に保管されます。",
    "nav.profile": "1    基本情報",
    "nav.summary": "2    概要",
    "nav.experience": "3    職務経歴",
    "nav.education": "4    学歴",
    "nav.preview": "5    プレビュー",

    "profile.title": "基本情報",
    "profile.subtitle": "履歴書の冒頭に表示される主要な情報です。",
    "profile.name": "氏名",
    "profile.headline": "職種・肩書き",
    "profile.location": "所在地",
    "profile.email": "メールアドレス",
    "profile.linkedin": "LinkedIn またはウェブサイト",
    "profile.skills": "スキル",
    "profile.skills_hint": "1 行に 1 つ",
    "profile.languages": "語学",
    "profile.languages_hint": "1 行に 1 つ",

    "summary.title": "概要",
    "summary.subtitle": "段落の区切りには空行を使います。",
    "summary.label": "職務要約",
    "summary.character_count": "文字数: {count}",

    "experience.title": "職務経歴",
    "experience.subtitle": "同じ会社での複数の役職は 1 社にまとめられます。",
    "experience.add_action": "+  会社を追加",
    "experience.add_title": "会社の追加",
    "experience.edit_title": "会社の編集",
    "experience.edit_subtitle": "この会社での役職は次の画面で追加します。",
    "experience.company": "会社名",
    "experience.role": "役職",
    "experience.place": "勤務地",
    "experience.add_position": "+  役職を追加",
    "experience.position_add_title": "役職の追加",
    "experience.position_edit_title": "役職の編集",
    "experience.position_subtitle": "役割、業務内容、測定可能な成果を記述してください。",
    "experience.date_start": "開始",
    "experience.date_end": "終了",
    "experience.current": "現在も在籍中",
    "experience.month": "月",
    "experience.year": "年",
    "experience.no_positions": "役職がまだありません",
    "experience.save_position": "役職を保存",
    "experience.intro": "役割またはプロジェクトの説明",
    "experience.work": "主な業務",
    "experience.results": "実績",
    "experience.line_hint": "1 行に 1 項目",
    "experience.save_entry": "保存",
    "experience.empty_title": "職歴がまだありません",
    "experience.empty_subtitle": "会社を追加し、そこで務めた役職を登録しましょう。",
    "experience.empty_action": "+  最初の会社を追加",
    "experience.untitled_role": "役職未設定",
    "experience.no_company": "会社名が未入力",
    "experience.action.edit": "編集",
    "experience.action.delete": "削除",

    "education.title": "学歴",
    "education.subtitle": "この履歴書に最も関連する学歴を追加してください。",
    "education.action": "プレビュー  →",
    "education.institution": "学校名",
    "education.qualification": "学位・在学期間",

    "preview.title": "プレビュー",
    "preview.subtitle": "全ページを確認し、書き出す前に言語とサイドバーの色を設定してください。",
    "preview.sidebar_colour": "サイドバーの色",
    "preview.cv_language": "履歴書の言語",
    "preview.cv_language_hint": "印刷されるセクション見出しの言語です。",

    "theme.linkedin": "LinkedIn グレー",
    "theme.olive-deep": "ダークオリーブ",
    "theme.olive-soft": "ライトオリーブ",
    "theme.forest": "フォレストグリーン",
    "theme.mint": "ミント",
    "theme.ink": "インクブラック",
    "theme.midnight": "ミッドナイトネイビー",

    "settings.title": "設定",
    "settings.interface_language": "インターフェースの言語",
    "settings.interface_hint": "このアプリの表示言語です。履歴書ごとの言語は「プレビュー」ステップで選択します。",
    "settings.example_json": "サンプル JSON",
    "settings.example_json_hint": "読み込み用のフォーマットにサンプルデータを入れたものです。このファイルと自分の職務経歴を AI チャットに渡せば、そのまま読み込める履歴書が組み立てられます。入力し直す必要はありません。",
    "settings.example_json_save": "サンプル JSON を保存…",
    "settings.example_json_prompt_hint": "ファイルと一緒に送るプロンプト:",
    "settings.example_json_prompt": "添付は CV Builder アプリが使う JSON フォーマットに、サンプルデータを入れたものです。以下は私の職務経歴です。まったく同じ構造の JSON ファイルを 1 つ作り、私のデータで埋めてください。すべてのキーと入れ子の階層はそのまま維持し、項目の追加や名前の変更はしないでください。内容は以下の私の文章と同じ言語で書いてください。JSON のみを返し、説明は不要です。",
    "settings.copy_prompt": "プロンプトをコピー",
    "settings.prompt_copied": "コピーしました ✓",

    "dialog.rename.title": "履歴書の名前を変更",
    "dialog.rename.text": "この履歴書の新しい名前を入力してください:",
    "dialog.delete.title": "履歴書を削除",
    "dialog.delete.message": "「{title}」をこの端末から削除しますか？",
    "dialog.delete.detail": "この操作は取り消せません。バックアップが必要な場合は先に JSON を書き出してください。",
    "dialog.delete_entry.title": "項目を削除",
    "dialog.delete_entry.message": "この会社と、そのすべての役職を削除しますか？",
    "dialog.select_entry.title": "項目を選択",
    "dialog.select_entry.message": "先に職歴を選択してください。",
    "dialog.missing_info.title": "入力が不足しています",
    "dialog.missing_info.message": "会社名は必須です。",
    "dialog.delete_position.title": "役職を削除",
    "dialog.delete_position.message": "この役職を削除しますか？",
    "dialog.missing_position.message": "役職と開始年月は必須です。",
    "dialog.invalid_dates.title": "期間を確認してください",
    "dialog.invalid_dates.message": "終了年月は開始年月より前にはできません。",
    "dialog.missing_name.title": "氏名が未入力",
    "dialog.missing_name.message": "PDF を作成する前に氏名を入力してください。",
    "dialog.import.title": "履歴書 JSON を読み込む",
    "dialog.export_json.title": "履歴書を JSON に書き出す",
    "dialog.example.title": "サンプル履歴書を JSON で保存",
    "dialog.example_saved.title": "サンプル JSON を保存しました",
    "dialog.example_saved.message": "このファイルを編集して CV Builder に読み込み直してください:\n{path}",
    "dialog.export_pdf.title": "PDF を書き出す",
    "dialog.pdf_created.title": "PDF を作成しました",
    "dialog.pdf_created.message": "履歴書の保存先:\n{path}",
    "error.library_open": "履歴書ライブラリを開けませんでした",
    "error.create": "履歴書を作成できませんでした",
    "error.open": "履歴書を開けませんでした",
    "error.rename": "名前を変更できませんでした",
    "error.duplicate": "複製できませんでした",
    "error.delete": "削除できませんでした",
    "error.import": "JSON を読み込めませんでした",
    "error.export_json": "JSON を書き出せませんでした",
    "error.example": "サンプル JSON を保存できませんでした",
    "error.pdf": "PDF を作成できませんでした",

    "filetype.json": "CV Builder JSON",
    "filetype.pdf": "PDF ドキュメント",
    "filetype.all": "すべてのファイル",
    "file.example_json": "cv-builder-example.json",
    "file.default_cv": "my-cv",
    "file.pdf_name": "{name} - 履歴書.pdf",

    "placeholder.name": "氏名",
    "placeholder.headline": "職種 | 専門分野 | 提供価値",
    "placeholder.location": "都市、国",
    "placeholder.email": "your.email@example.com",
    "placeholder.linkedin": "linkedin.com/in/your-profile",
    "placeholder.skills": "スキル 1\nスキル 2\nスキル 3",
    "placeholder.languages": "英語 - C1\nスペイン語 - B2",
    "placeholder.summary": (
        "これまでの経歴と主な専門分野について簡潔に書いてください。"
        "\n\n関わってきたチーム、プロジェクト、プロダクトについて説明してください。"
        "\n\n最も関連性の高い成果と専門領域を強調してください。"
    ),
    "placeholder.company": "現在または直近の勤務先",
    "placeholder.role": "役職",
    "placeholder.place": "都市、国",
    "placeholder.intro": "役割またはプロジェクトを一文で説明してください。",
    "placeholder.work": "主な業務を記述してください。\nもう一つの貢献を記述してください。",
    "placeholder.results": "測定可能な成果やビジネスへの影響を記述してください。",
    "placeholder.institution": "大学・学校名",
    "placeholder.qualification": "学位または資格（YYYY 年 - YYYY 年）",
}
