"""Korean interface strings."""
from __future__ import annotations


STRINGS: dict[str, str] = {
    "app.name": "CV Builder",
    "section.step": "{total}단계 중 {current}단계",
    "action.cancel": "취소",
    "action.done": "완료",

    "status.library": "로컬 이력서 보관함",
    "status.saving": "저장 중…",
    "status.saved": "저장됨",
    "status.save_failed": "저장하지 못했습니다",
    "status.exporting_pdf": "PDF 내보내는 중…",
    "status.exported": "내보냄 · {name}",
    "status.pdf_failed": "PDF 내보내기 실패",
    "status.json_exported": "JSON 내보냄",
    "status.progress": "{percent}% 완료",

    "library.subtitle": "내 이력서 보관함",
    "library.eyebrow": "내 문서",
    "library.title": "계속할 이력서를 선택하세요",
    "library.import_json": "JSON 가져오기",
    "library.new_cv": "+  새 이력서",
    "library.settings": "설정",
    "library.empty_title": "첫 이력서를 만들어 보세요",
    "library.empty_subtitle": "변경 사항은 이 기기에 자동으로 저장됩니다.",
    "library.empty_action": "+  이력서 만들기",
    "library.card_meta": "{person}  ·  {percent}% 완료",
    "library.card_updated": "업데이트 {date}",
    "library.recently_updated": "최근 업데이트됨",
    "library.no_name": "이름이 아직 없습니다",
    "library.preview_failed": "문서를 표시할 수 없습니다",
    "library.action.open": "열기",
    "library.action.pdf": "PDF",
    "library.action.rename": "이름 변경",
    "library.action.duplicate": "복제",
    "library.action.delete": "삭제",

    "editor.all_cvs": "모든 이력서",
    "editor.export_json": "JSON 내보내기",
    "editor.export_pdf": "PDF 내보내기",
    "editor.build_your_cv": "이력서 작성",
    "editor.privacy": "로컬 및 비공개\n데이터는 이 기기에 남습니다.",
    "nav.profile": "1    프로필",
    "nav.summary": "2    소개",
    "nav.experience": "3    경력",
    "nav.education": "4    학력",
    "nav.preview": "5    미리보기",

    "profile.title": "프로필",
    "profile.subtitle": "이력서 상단에 표시되는 핵심 정보입니다.",
    "profile.name": "이름",
    "profile.headline": "직무 헤드라인",
    "profile.location": "지역",
    "profile.email": "이메일",
    "profile.linkedin": "LinkedIn 또는 웹사이트",
    "profile.skills": "핵심 역량",
    "profile.skills_hint": "한 줄에 하나씩",

    "summary.title": "소개",
    "summary.subtitle": "문단 사이는 빈 줄로 구분하세요.",
    "summary.label": "직무 요약",
    "summary.character_count": "글자 수: {count}",

    "experience.title": "경력",
    "experience.subtitle": "가장 관련성 높은 경력을 먼저 배치하세요.",
    "experience.add_action": "+  경력 추가",
    "experience.add_title": "경력 추가",
    "experience.edit_title": "경력 편집",
    "experience.edit_subtitle": "역할, 주요 업무, 측정 가능한 성과를 작성하세요.",
    "experience.company": "회사",
    "experience.role": "직책",
    "experience.dates": "기간",
    "experience.duration": "총 재직 기간",
    "experience.place": "근무지",
    "experience.intro": "역할 또는 프로젝트 설명",
    "experience.work": "주요 업무",
    "experience.results": "성과",
    "experience.line_hint": "한 줄에 한 항목",
    "experience.save_entry": "저장",
    "experience.empty_title": "아직 경력이 없습니다",
    "experience.empty_subtitle": "경력을 추가해 업무와 성과를 보여주세요.",
    "experience.empty_action": "+  첫 경력 추가",
    "experience.untitled_role": "직책 미입력",
    "experience.no_company": "회사 미입력",
    "experience.action.edit": "편집",
    "experience.action.delete": "삭제",

    "education.title": "학력",
    "education.subtitle": "이 이력서에 가장 관련 있는 학력을 추가하세요.",
    "education.action": "미리보기  →",
    "education.institution": "학교명",
    "education.qualification": "학위 및 기간",

    "preview.title": "미리보기",
    "preview.subtitle": "모든 페이지를 확인한 뒤, 내보내기 전에 언어와 사이드바 색상을 설정하세요.",
    "preview.sidebar_colour": "사이드바 색상",
    "preview.cv_language": "이력서 언어",
    "preview.cv_language_hint": "인쇄되는 섹션 제목의 언어입니다.",

    "theme.linkedin": "LinkedIn 그레이",
    "theme.olive-deep": "다크 올리브",
    "theme.olive-soft": "라이트 올리브",
    "theme.forest": "포레스트 그린",
    "theme.mint": "민트",
    "theme.ink": "잉크 블랙",
    "theme.midnight": "미드나이트 네이비",

    "settings.title": "설정",
    "settings.interface_language": "인터페이스 언어",
    "settings.interface_hint": "이 앱의 표시 언어입니다. 각 이력서의 언어는 ‘미리보기’ 단계에서 선택합니다.",
    "settings.example_json": "예제 JSON",
    "settings.example_json_hint": "샘플 데이터가 채워진 가져오기 형식입니다. 이 파일을 경력 내용과 함께 AI 채팅에 주면 여기로 바로 가져올 수 있는 이력서를 만들어 줍니다. 다시 입력할 필요가 없습니다.",
    "settings.example_json_save": "예제 JSON 저장…",
    "settings.example_json_prompt_hint": "파일과 함께 보낼 프롬프트:",
    "settings.example_json_prompt": "첨부한 것은 CV Builder 앱이 사용하는 JSON 형식에 샘플 데이터를 채운 것입니다. 아래는 제 경력입니다. 똑같은 구조의 JSON 파일 하나를 만들어 제 데이터로 채워 주세요. 모든 키와 중첩 구조는 그대로 유지하고, 필드를 추가하거나 이름을 바꾸지 마세요. 내용은 아래 제 글과 같은 언어로 작성해 주세요. 설명 없이 JSON만 반환해 주세요.",
    "settings.copy_prompt": "프롬프트 복사",
    "settings.prompt_copied": "복사됨 ✓",

    "dialog.rename.title": "이력서 이름 변경",
    "dialog.rename.text": "이 이력서의 새 이름을 입력하세요:",
    "dialog.delete.title": "이력서 삭제",
    "dialog.delete.message": "이 기기에서 ‘{title}’을(를) 삭제할까요?",
    "dialog.delete.detail": "되돌릴 수 없습니다. 백업이 필요하면 먼저 JSON을 내보내세요.",
    "dialog.delete_entry.title": "항목 삭제",
    "dialog.delete_entry.message": "이 경력 항목을 삭제할까요?",
    "dialog.select_entry.title": "항목 선택",
    "dialog.select_entry.message": "먼저 경력 항목을 선택하세요.",
    "dialog.missing_info.title": "정보 부족",
    "dialog.missing_info.message": "회사와 직책은 필수입니다.",
    "dialog.missing_name.title": "이름 없음",
    "dialog.missing_name.message": "PDF를 만들기 전에 이름을 입력하세요.",
    "dialog.import.title": "이력서 JSON 가져오기",
    "dialog.export_json.title": "이력서를 JSON으로 내보내기",
    "dialog.example.title": "예제 이력서를 JSON으로 저장",
    "dialog.example_saved.title": "예제 JSON 저장됨",
    "dialog.example_saved.message": "이 파일을 편집한 뒤 CV Builder로 다시 가져오세요:\n{path}",
    "dialog.export_pdf.title": "PDF 내보내기",
    "dialog.pdf_created.title": "PDF 생성됨",
    "dialog.pdf_created.message": "이력서가 저장된 위치:\n{path}",
    "error.library_open": "이력서 보관함을 열 수 없습니다",
    "error.create": "이력서를 만들 수 없습니다",
    "error.open": "이력서를 열 수 없습니다",
    "error.rename": "이름을 변경할 수 없습니다",
    "error.duplicate": "복제할 수 없습니다",
    "error.delete": "삭제할 수 없습니다",
    "error.import": "JSON을 가져올 수 없습니다",
    "error.export_json": "JSON을 내보낼 수 없습니다",
    "error.example": "예제 JSON을 저장할 수 없습니다",
    "error.pdf": "PDF를 생성할 수 없습니다",

    "filetype.json": "CV Builder JSON",
    "filetype.pdf": "PDF 문서",
    "filetype.all": "모든 파일",
    "file.example_json": "cv-builder-example.json",
    "file.default_cv": "my-cv",
    "file.pdf_name": "{name} - 이력서.pdf",

    "placeholder.name": "이름",
    "placeholder.headline": "직무 | 전문 분야 | 핵심 강점",
    "placeholder.location": "도시, 국가",
    "placeholder.email": "your.email@example.com",
    "placeholder.linkedin": "linkedin.com/in/your-profile",
    "placeholder.skills": "역량 1\n역량 2\n역량 3",
    "placeholder.summary": (
        "경력과 주요 전문 분야를 간단히 소개해 주세요."
        "\n\n함께 일한 팀, 프로젝트, 제품을 설명해 주세요."
        "\n\n가장 관련성 높은 성과와 전문 영역을 강조해 주세요."
    ),
    "placeholder.company": "현재 또는 최근 회사",
    "placeholder.duration": "X년 X개월",
    "placeholder.role": "직책",
    "placeholder.dates": "YYYY년 M월 - 현재",
    "placeholder.place": "도시, 국가",
    "placeholder.intro": "역할이나 프로젝트를 한 문장으로 설명하세요.",
    "placeholder.work": "핵심 업무를 작성하세요.\n또 다른 기여를 작성하세요.",
    "placeholder.results": "측정 가능한 성과나 비즈니스 임팩트를 작성하세요.",
    "placeholder.institution": "대학교 또는 학교명",
    "placeholder.qualification": "학위 또는 자격 (YYYY - YYYY)",
}
