"""Russian interface strings."""
from __future__ import annotations


STRINGS: dict[str, str] = {
    "app.name": "CV Builder",
    "section.step": "Шаг {current} из {total}",
    "action.cancel": "Отмена",
    "action.done": "Готово",

    "status.library": "Локальная библиотека CV",
    "status.saving": "Сохранение…",
    "status.saved": "Сохранено",
    "status.save_failed": "Не удалось сохранить",
    "status.exporting_pdf": "Экспорт PDF…",
    "status.exported": "Экспортировано · {name}",
    "status.pdf_failed": "Не удалось экспортировать PDF",
    "status.json_exported": "JSON экспортирован",
    "status.progress": "Заполнено на {percent}%",

    "library.subtitle": "Ваша библиотека резюме",
    "library.eyebrow": "ВАШИ ДОКУМЕНТЫ",
    "library.title": "Выберите резюме, чтобы продолжить",
    "library.import_json": "Импорт JSON",
    "library.new_cv": "+  Новое резюме",
    "library.settings": "Настройки",
    "library.empty_title": "Создайте первое резюме",
    "library.empty_subtitle": "Изменения сохраняются автоматически на этом устройстве.",
    "library.empty_action": "+  Создать резюме",
    "library.card_meta": "{person}  ·  заполнено на {percent}%",
    "library.card_updated": "Обновлено {date}",
    "library.recently_updated": "Обновлено недавно",
    "library.no_name": "Имя ещё не указано",
    "library.preview_failed": "Не удалось показать документ",
    "library.action.open": "Открыть",
    "library.action.pdf": "PDF",
    "library.action.rename": "Переименовать",
    "library.action.duplicate": "Дублировать",
    "library.action.delete": "Удалить",

    "editor.all_cvs": "Все резюме",
    "editor.export_json": "Экспорт JSON",
    "editor.export_pdf": "Экспорт PDF",
    "editor.build_your_cv": "СОБЕРИТЕ РЕЗЮМЕ",
    "editor.privacy": "Локально и приватно\nДанные остаются на этом устройстве.",
    "nav.profile": "1    Профиль",
    "nav.summary": "2    О себе",
    "nav.experience": "3    Опыт",
    "nav.education": "4    Образование",
    "nav.preview": "5    Просмотр",

    "profile.title": "Профиль",
    "profile.subtitle": "Основные данные в верхней части резюме.",
    "profile.name": "Имя и фамилия",
    "profile.headline": "Профессиональный заголовок",
    "profile.location": "Город",
    "profile.email": "Email",
    "profile.linkedin": "LinkedIn или сайт",
    "profile.skills": "Ключевые навыки",
    "profile.skills_hint": "По одному навыку в строке",

    "summary.title": "О себе",
    "summary.subtitle": "Разделяйте абзацы пустой строкой.",
    "summary.label": "Профессиональное описание",
    "summary.character_count": "Символов: {count}",

    "experience.title": "Опыт работы",
    "experience.subtitle": "Самое релевантное место работы — первым.",
    "experience.add_action": "+  Добавить место",
    "experience.add_title": "Новое место работы",
    "experience.edit_title": "Редактирование места работы",
    "experience.edit_subtitle": "Опишите роль, обязанности и измеримые результаты.",
    "experience.company": "Компания",
    "experience.role": "Должность",
    "experience.dates": "Период",
    "experience.duration": "Общая длительность",
    "experience.place": "Город",
    "experience.intro": "Описание роли или проекта",
    "experience.work": "Ключевые обязанности",
    "experience.results": "Результаты",
    "experience.line_hint": "По одному пункту в строке",
    "experience.save_entry": "Сохранить",
    "experience.empty_title": "Опыт работы пока не добавлен",
    "experience.empty_subtitle": "Добавьте место работы, чтобы показать обязанности и результаты.",
    "experience.empty_action": "+  Добавить первое место",
    "experience.untitled_role": "Должность не указана",
    "experience.no_company": "Компания не указана",
    "experience.action.edit": "Изменить",
    "experience.action.delete": "Удалить",

    "education.title": "Образование",
    "education.subtitle": "Добавьте квалификацию, наиболее подходящую этому резюме.",
    "education.action": "Просмотр  →",
    "education.institution": "Учебное заведение",
    "education.qualification": "Квалификация и годы",

    "preview.title": "Просмотр",
    "preview.subtitle": "Проверьте все страницы, затем задайте язык и цвет сайдбара перед экспортом.",
    "preview.sidebar_colour": "ЦВЕТ САЙДБАРА",
    "preview.cv_language": "ЯЗЫК РЕЗЮМЕ",
    "preview.cv_language_hint": "Язык печатных заголовков разделов.",

    "theme.linkedin": "Серый LinkedIn",
    "theme.olive-deep": "Тёмная олива",
    "theme.olive-soft": "Светлая олива",
    "theme.forest": "Лесной зелёный",
    "theme.mint": "Мятный",
    "theme.ink": "Чернильный чёрный",
    "theme.midnight": "Полуночный синий",

    "settings.title": "Настройки",
    "settings.interface_language": "Язык интерфейса",
    "settings.interface_hint": "Язык этого приложения. У каждого резюме есть собственный язык — он выбирается на шаге «Просмотр».",
    "settings.example_json": "Пример JSON",
    "settings.example_json_hint": "Формат импорта, заполненный образцом данных. Передайте этот файл в любой ИИ-чат вместе со своей историей работы — он соберёт готовое резюме, которое вы импортируете обратно, без ручного ввода.",
    "settings.example_json_save": "Сохранить пример JSON…",
    "settings.example_json_prompt_hint": "Промпт, который можно отправить вместе с файлом:",
    "settings.example_json_prompt": "Во вложении — формат JSON, который использует приложение CV Builder, заполненный образцом данных. Ниже — моя история работы. Собери один JSON-файл ровно с такой же структурой, заполненный моими данными. Сохрани все ключи и уровни вложенности без изменений, не добавляй и не переименовывай поля, а содержимое напиши на том языке, на котором написан мой текст ниже. Верни только JSON, без комментариев.",
    "settings.copy_prompt": "Скопировать промпт",
    "settings.prompt_copied": "Скопировано ✓",

    "dialog.rename.title": "Переименовать резюме",
    "dialog.rename.text": "Введите новое название резюме:",
    "dialog.delete.title": "Удалить резюме",
    "dialog.delete.message": "Удалить «{title}» с этого устройства?",
    "dialog.delete.detail": "Это действие необратимо. Экспортируйте JSON, если нужна резервная копия.",
    "dialog.delete_entry.title": "Удалить запись",
    "dialog.delete_entry.message": "Удалить эту запись об опыте работы?",
    "dialog.select_entry.title": "Выберите запись",
    "dialog.select_entry.message": "Сначала выберите запись об опыте работы.",
    "dialog.missing_info.title": "Не хватает данных",
    "dialog.missing_info.message": "Компания и должность обязательны.",
    "dialog.missing_name.title": "Не указано имя",
    "dialog.missing_name.message": "Укажите имя перед созданием PDF.",
    "dialog.import.title": "Импорт резюме из JSON",
    "dialog.export_json.title": "Экспорт резюме в JSON",
    "dialog.example.title": "Сохранить пример резюме в JSON",
    "dialog.example_saved.title": "Пример JSON сохранён",
    "dialog.example_saved.message": "Отредактируйте этот файл и импортируйте обратно в CV Builder:\n{path}",
    "dialog.export_pdf.title": "Экспорт PDF",
    "dialog.pdf_created.title": "PDF создан",
    "dialog.pdf_created.message": "Резюме сохранено в:\n{path}",
    "error.library_open": "Не удалось открыть библиотеку резюме",
    "error.create": "Не удалось создать резюме",
    "error.open": "Не удалось открыть резюме",
    "error.rename": "Не удалось переименовать резюме",
    "error.duplicate": "Не удалось дублировать резюме",
    "error.delete": "Не удалось удалить резюме",
    "error.import": "Не удалось импортировать JSON",
    "error.export_json": "Не удалось экспортировать JSON",
    "error.example": "Не удалось сохранить пример JSON",
    "error.pdf": "Не удалось создать PDF",

    "filetype.json": "CV Builder JSON",
    "filetype.pdf": "Документ PDF",
    "filetype.all": "Все файлы",
    "file.example_json": "cv-builder-example.json",
    "file.default_cv": "moe-rezume",
    "file.pdf_name": "{name} - CV.pdf",

    "placeholder.name": "ВАШЕ ИМЯ",
    "placeholder.headline": "ВАША ДОЛЖНОСТЬ | СПЕЦИАЛИЗАЦИЯ | КЛЮЧЕВАЯ ЦЕННОСТЬ",
    "placeholder.location": "ВАШ ГОРОД, ВАША СТРАНА",
    "placeholder.email": "your.email@example.com",
    "placeholder.linkedin": "linkedin.com/in/your-profile",
    "placeholder.skills": "НАВЫК ОДИН\nНАВЫК ДВА\nНАВЫК ТРИ",
    "placeholder.summary": (
        "Коротко расскажите о своём профессиональном опыте и основной "
        "экспертизе.\n\nОпишите команды, проекты или продукты, с которыми вы "
        "работали.\n\nВыделите самые значимые результаты и области "
        "специализации."
    ),
    "placeholder.company": "ТЕКУЩАЯ ИЛИ ПОСЛЕДНЯЯ КОМПАНИЯ",
    "placeholder.duration": "X ЛЕТ X МЕСЯЦЕВ",
    "placeholder.role": "ВАША ДОЛЖНОСТЬ",
    "placeholder.dates": "МЕСЯЦ ГОД — НАСТОЯЩЕЕ ВРЕМЯ",
    "placeholder.place": "ГОРОД, СТРАНА",
    "placeholder.intro": "Добавьте описание роли или проекта одним предложением.",
    "placeholder.work": "Опишите ключевую обязанность.\nОпишите ещё один вклад.",
    "placeholder.results": "Опишите измеримый результат или влияние на бизнес.",
    "placeholder.institution": "УНИВЕРСИТЕТ ИЛИ ШКОЛА",
    "placeholder.qualification": "СТЕПЕНЬ ИЛИ КВАЛИФИКАЦИЯ (ГОД — ГОД)",
}
