"""Simplified Chinese interface strings."""
from __future__ import annotations


STRINGS: dict[str, str] = {
    "app.name": "CV Builder",
    "section.step": "第 {current} 步，共 {total} 步",
    "action.cancel": "取消",
    "action.done": "完成",

    "status.library": "本地简历库",
    "status.saving": "正在保存…",
    "status.saved": "已保存",
    "status.save_failed": "保存失败",
    "status.exporting_pdf": "正在导出 PDF…",
    "status.exported": "已导出 · {name}",
    "status.pdf_failed": "PDF 导出失败",
    "status.json_exported": "已导出 JSON",
    "status.progress": "已完成 {percent}%",

    "library.subtitle": "你的简历库",
    "library.eyebrow": "你的文档",
    "library.title": "选择一份简历继续",
    "library.import_json": "导入 JSON",
    "library.new_cv": "+  新建简历",
    "library.settings": "设置",
    "library.empty_title": "创建你的第一份简历",
    "library.empty_subtitle": "更改会自动保存在本设备上。",
    "library.empty_action": "+  创建简历",
    "library.card_meta": "{person}  ·  已完成 {percent}%",
    "library.card_updated": "更新于 {date}",
    "library.recently_updated": "最近更新",
    "library.no_name": "尚未填写姓名",
    "library.preview_failed": "无法预览该文档",
    "library.action.open": "打开",
    "library.action.pdf": "PDF",
    "library.action.rename": "重命名",
    "library.action.duplicate": "复制",
    "library.action.delete": "删除",

    "editor.all_cvs": "全部简历",
    "editor.export_json": "导出 JSON",
    "editor.export_pdf": "导出 PDF",
    "editor.build_your_cv": "创建你的简历",
    "editor.privacy": "本地且私密\n数据只保存在本设备上。",
    "nav.profile": "1    个人信息",
    "nav.summary": "2    简介",
    "nav.experience": "3    工作经历",
    "nav.education": "4    教育背景",
    "nav.preview": "5    预览",

    "profile.title": "个人信息",
    "profile.subtitle": "显示在简历顶部的关键信息。",
    "profile.name": "姓名",
    "profile.headline": "职业头衔",
    "profile.location": "所在地",
    "profile.email": "电子邮箱",
    "profile.linkedin": "LinkedIn 或个人网站",
    "profile.skills": "核心技能",
    "profile.skills_hint": "每行一项",

    "summary.title": "简介",
    "summary.subtitle": "段落之间用空行分隔。",
    "summary.label": "职业简介",
    "summary.character_count": "字数：{count}",

    "experience.title": "工作经历",
    "experience.subtitle": "把最相关的职位放在最前面。",
    "experience.add_action": "+  添加经历",
    "experience.add_title": "添加工作经历",
    "experience.edit_title": "编辑工作经历",
    "experience.edit_subtitle": "描述职责、工作内容和可衡量的成果。",
    "experience.company": "公司",
    "experience.role": "职位",
    "experience.dates": "时间",
    "experience.duration": "在职时长",
    "experience.place": "工作地点",
    "experience.intro": "职位或项目描述",
    "experience.work": "主要职责",
    "experience.results": "工作成果",
    "experience.line_hint": "每行一项",
    "experience.save_entry": "保存",
    "experience.empty_title": "尚未添加工作经历",
    "experience.empty_subtitle": "添加一段经历，展示你的职责与影响力。",
    "experience.empty_action": "+  添加第一段经历",
    "experience.untitled_role": "未填写职位",
    "experience.no_company": "未填写公司",
    "experience.action.edit": "编辑",
    "experience.action.delete": "删除",

    "education.title": "教育背景",
    "education.subtitle": "添加与本份简历最相关的学历。",
    "education.action": "预览  →",
    "education.institution": "学校名称",
    "education.qualification": "学位与时间",

    "preview.title": "预览",
    "preview.subtitle": "请检查每一页，并在导出前设置语言和侧栏颜色。",
    "preview.sidebar_colour": "侧栏颜色",
    "preview.cv_language": "简历语言",
    "preview.cv_language_hint": "打印出的各章节标题所用语言。",

    "theme.linkedin": "LinkedIn 灰",
    "theme.olive-deep": "深橄榄绿",
    "theme.olive-soft": "浅橄榄绿",
    "theme.forest": "森林绿",
    "theme.mint": "薄荷绿",
    "theme.ink": "墨黑",
    "theme.midnight": "午夜蓝",

    "settings.title": "设置",
    "settings.interface_language": "界面语言",
    "settings.interface_hint": "本应用的显示语言。每份简历有各自的语言，在“预览”步骤中选择。",
    "settings.example_json": "示例 JSON",
    "settings.example_json_hint": "填入示例数据的导入格式。把这个文件连同你的工作经历交给任意 AI 对话，它就能生成一份可直接导回本应用的完整简历，无需重新录入。",
    "settings.example_json_save": "保存示例 JSON…",
    "settings.example_json_prompt_hint": "随文件一起发送的提示词：",
    "settings.example_json_prompt": "附件是 CV Builder 应用使用的 JSON 格式，已填入示例数据。下面是我的工作经历。请生成一个结构完全相同的 JSON 文件，用我的数据填充。保持所有键名和嵌套层级不变，不要新增或重命名字段，内容请使用我下文所用的语言。只返回 JSON，不要任何说明。",
    "settings.copy_prompt": "复制提示词",
    "settings.prompt_copied": "已复制 ✓",

    "dialog.rename.title": "重命名简历",
    "dialog.rename.text": "请输入这份简历的新名称：",
    "dialog.delete.title": "删除简历",
    "dialog.delete.message": "确定从本设备删除“{title}”吗？",
    "dialog.delete.detail": "此操作无法撤销。如需备份，请先导出它的 JSON。",
    "dialog.delete_entry.title": "删除条目",
    "dialog.delete_entry.message": "确定删除这条工作经历吗？",
    "dialog.select_entry.title": "选择条目",
    "dialog.select_entry.message": "请先选择一条工作经历。",
    "dialog.missing_info.title": "信息不完整",
    "dialog.missing_info.message": "公司和职位为必填项。",
    "dialog.missing_name.title": "缺少姓名",
    "dialog.missing_name.message": "生成 PDF 前请先填写姓名。",
    "dialog.import.title": "导入简历 JSON",
    "dialog.export_json.title": "导出简历为 JSON",
    "dialog.example.title": "保存示例简历 JSON",
    "dialog.example_saved.title": "示例 JSON 已保存",
    "dialog.example_saved.message": "编辑此文件后再导入回 CV Builder：\n{path}",
    "dialog.export_pdf.title": "导出 PDF",
    "dialog.pdf_created.title": "PDF 已创建",
    "dialog.pdf_created.message": "简历已保存至：\n{path}",
    "error.library_open": "无法打开简历库",
    "error.create": "无法创建简历",
    "error.open": "无法打开简历",
    "error.rename": "无法重命名简历",
    "error.duplicate": "无法复制简历",
    "error.delete": "无法删除简历",
    "error.import": "无法导入 JSON",
    "error.export_json": "无法导出 JSON",
    "error.example": "无法保存示例 JSON",
    "error.pdf": "无法生成 PDF",

    "filetype.json": "CV Builder JSON",
    "filetype.pdf": "PDF 文档",
    "filetype.all": "所有文件",
    "file.example_json": "cv-builder-example.json",
    "file.default_cv": "my-cv",
    "file.pdf_name": "{name} - 简历.pdf",

    "placeholder.name": "你的姓名",
    "placeholder.headline": "你的职位 | 专业方向 | 核心价值",
    "placeholder.location": "城市，国家",
    "placeholder.email": "your.email@example.com",
    "placeholder.linkedin": "linkedin.com/in/your-profile",
    "placeholder.skills": "技能一\n技能二\n技能三",
    "placeholder.summary": (
        "简要介绍你的职业背景与主要专长。"
        "\n\n描述你参与过的团队、项目或产品。"
        "\n\n突出最相关的成果与专业领域。"
    ),
    "placeholder.company": "当前或最近任职的公司",
    "placeholder.duration": "X 年 X 个月",
    "placeholder.role": "你的职位",
    "placeholder.dates": "YYYY 年 M 月 - 至今",
    "placeholder.place": "城市，国家",
    "placeholder.intro": "用一句话描述该职位或项目。",
    "placeholder.work": "描述一项核心职责。\n描述另一项贡献。",
    "placeholder.results": "描述一项可衡量的成果或业务影响。",
    "placeholder.institution": "大学或学校名称",
    "placeholder.qualification": "学位或资格（YYYY - YYYY）",
}
