"""Traditional Chinese interface strings."""
from __future__ import annotations


STRINGS: dict[str, str] = {
    "app.name": "CV Builder",
    "section.step": "第 {current} 步，共 {total} 步",
    "action.cancel": "取消",
    "action.done": "完成",

    "status.library": "本機履歷庫",
    "status.saving": "儲存中…",
    "status.saved": "已儲存",
    "status.save_failed": "儲存失敗",
    "status.exporting_pdf": "正在匯出 PDF…",
    "status.exported": "已匯出 · {name}",
    "status.pdf_failed": "PDF 匯出失敗",
    "status.json_exported": "已匯出 JSON",
    "status.progress": "已完成 {percent}%",

    "library.subtitle": "你的履歷庫",
    "library.eyebrow": "你的文件",
    "library.title": "選擇一份履歷繼續",
    "library.import_json": "匯入 JSON",
    "library.new_cv": "+  新增履歷",
    "library.settings": "設定",
    "library.empty_title": "建立你的第一份履歷",
    "library.empty_subtitle": "變更會自動儲存在本裝置上。",
    "library.empty_action": "+  建立履歷",
    "library.card_meta": "{person}  ·  已完成 {percent}%",
    "library.card_updated": "更新於 {date}",
    "library.recently_updated": "最近更新",
    "library.no_name": "尚未填寫姓名",
    "library.preview_failed": "無法預覽此文件",
    "library.action.open": "開啟",
    "library.action.pdf": "PDF",
    "library.action.rename": "重新命名",
    "library.action.duplicate": "複製",
    "library.action.delete": "刪除",

    "editor.all_cvs": "全部履歷",
    "editor.export_json": "匯出 JSON",
    "editor.export_pdf": "匯出 PDF",
    "editor.build_your_cv": "建立你的履歷",
    "editor.privacy": "本機且私密\n資料只保存在本裝置上。",
    "nav.profile": "1    個人資料",
    "nav.summary": "2    簡介",
    "nav.experience": "3    工作經歷",
    "nav.education": "4    教育背景",
    "nav.preview": "5    預覽",

    "profile.title": "個人資料",
    "profile.subtitle": "顯示在履歷最上方的關鍵資訊。",
    "profile.name": "姓名",
    "profile.headline": "職業頭銜",
    "profile.location": "所在地",
    "profile.email": "電子郵件",
    "profile.linkedin": "LinkedIn 或個人網站",
    "profile.skills": "核心技能",
    "profile.skills_hint": "每行一項",

    "summary.title": "簡介",
    "summary.subtitle": "段落之間以空行分隔。",
    "summary.label": "職業簡介",
    "summary.character_count": "字數：{count}",

    "experience.title": "工作經歷",
    "experience.subtitle": "把最相關的職位放在最前面。",
    "experience.add_action": "+  新增經歷",
    "experience.add_title": "新增工作經歷",
    "experience.edit_title": "編輯工作經歷",
    "experience.edit_subtitle": "描述職責、工作內容與可衡量的成果。",
    "experience.company": "公司",
    "experience.role": "職位",
    "experience.dates": "時間",
    "experience.duration": "在職時長",
    "experience.place": "工作地點",
    "experience.intro": "職位或專案描述",
    "experience.work": "主要職責",
    "experience.results": "工作成果",
    "experience.line_hint": "每行一項",
    "experience.save_entry": "儲存",
    "experience.empty_title": "尚未新增工作經歷",
    "experience.empty_subtitle": "新增一段經歷，展示你的職責與影響力。",
    "experience.empty_action": "+  新增第一段經歷",
    "experience.untitled_role": "未填寫職位",
    "experience.no_company": "未填寫公司",
    "experience.action.edit": "編輯",
    "experience.action.delete": "刪除",

    "education.title": "教育背景",
    "education.subtitle": "新增與這份履歷最相關的學歷。",
    "education.action": "預覽  →",
    "education.institution": "學校名稱",
    "education.qualification": "學位與時間",

    "preview.title": "預覽",
    "preview.subtitle": "請檢查每一頁，並在匯出前設定語言與側欄顏色。",
    "preview.sidebar_colour": "側欄顏色",
    "preview.cv_language": "履歷語言",
    "preview.cv_language_hint": "列印出的各章節標題所用語言。",

    "theme.linkedin": "LinkedIn 灰",
    "theme.olive-deep": "深橄欖綠",
    "theme.olive-soft": "淺橄欖綠",
    "theme.forest": "森林綠",
    "theme.mint": "薄荷綠",
    "theme.ink": "墨黑",
    "theme.midnight": "午夜藍",

    "settings.title": "設定",
    "settings.interface_language": "介面語言",
    "settings.interface_hint": "本應用程式的顯示語言。每份履歷有各自的語言，於「預覽」步驟中選擇。",
    "settings.example_json": "範例 JSON",
    "settings.example_json_hint": "填入範例資料的匯入格式。把這個檔案連同你的工作經歷交給任意 AI 對話，它就能產生一份可直接匯回本應用的完整履歷，不必重新輸入。",
    "settings.example_json_save": "儲存範例 JSON…",
    "settings.example_json_prompt_hint": "隨檔案一起傳送的提示詞：",
    "settings.example_json_prompt": "附件是 CV Builder 應用程式使用的 JSON 格式，已填入範例資料。下面是我的工作經歷。請產生一個結構完全相同的 JSON 檔案，用我的資料填入。保持所有鍵名與巢狀層級不變，不要新增或重新命名欄位，內容請使用我下文所用的語言。只回傳 JSON，不要任何說明。",
    "settings.copy_prompt": "複製提示詞",
    "settings.prompt_copied": "已複製 ✓",

    "dialog.rename.title": "重新命名履歷",
    "dialog.rename.text": "請輸入這份履歷的新名稱：",
    "dialog.delete.title": "刪除履歷",
    "dialog.delete.message": "確定要從本裝置刪除「{title}」嗎？",
    "dialog.delete.detail": "此操作無法復原。若需要備份，請先匯出它的 JSON。",
    "dialog.delete_entry.title": "刪除項目",
    "dialog.delete_entry.message": "確定要刪除這筆工作經歷嗎？",
    "dialog.select_entry.title": "選擇項目",
    "dialog.select_entry.message": "請先選擇一筆工作經歷。",
    "dialog.missing_info.title": "資訊不完整",
    "dialog.missing_info.message": "公司與職位為必填欄位。",
    "dialog.missing_name.title": "缺少姓名",
    "dialog.missing_name.message": "產生 PDF 前請先填寫姓名。",
    "dialog.import.title": "匯入履歷 JSON",
    "dialog.export_json.title": "將履歷匯出為 JSON",
    "dialog.example.title": "儲存範例履歷 JSON",
    "dialog.example_saved.title": "範例 JSON 已儲存",
    "dialog.example_saved.message": "編輯此檔案後再匯入回 CV Builder：\n{path}",
    "dialog.export_pdf.title": "匯出 PDF",
    "dialog.pdf_created.title": "PDF 已建立",
    "dialog.pdf_created.message": "履歷已儲存至：\n{path}",
    "error.library_open": "無法開啟履歷庫",
    "error.create": "無法建立履歷",
    "error.open": "無法開啟履歷",
    "error.rename": "無法重新命名履歷",
    "error.duplicate": "無法複製履歷",
    "error.delete": "無法刪除履歷",
    "error.import": "無法匯入 JSON",
    "error.export_json": "無法匯出 JSON",
    "error.example": "無法儲存範例 JSON",
    "error.pdf": "無法產生 PDF",

    "filetype.json": "CV Builder JSON",
    "filetype.pdf": "PDF 文件",
    "filetype.all": "所有檔案",
    "file.example_json": "cv-builder-example.json",
    "file.default_cv": "my-cv",
    "file.pdf_name": "{name} - 履歷.pdf",

    "placeholder.name": "你的姓名",
    "placeholder.headline": "你的職位 | 專業方向 | 核心價值",
    "placeholder.location": "城市，國家",
    "placeholder.email": "your.email@example.com",
    "placeholder.linkedin": "linkedin.com/in/your-profile",
    "placeholder.skills": "技能一\n技能二\n技能三",
    "placeholder.summary": (
        "簡要介紹你的職業背景與主要專長。"
        "\n\n描述你參與過的團隊、專案或產品。"
        "\n\n突顯最相關的成果與專業領域。"
    ),
    "placeholder.company": "目前或最近任職的公司",
    "placeholder.duration": "X 年 X 個月",
    "placeholder.role": "你的職位",
    "placeholder.dates": "YYYY 年 M 月 - 至今",
    "placeholder.place": "城市，國家",
    "placeholder.intro": "用一句話描述該職位或專案。",
    "placeholder.work": "描述一項核心職責。\n描述另一項貢獻。",
    "placeholder.results": "描述一項可衡量的成果或業務影響。",
    "placeholder.institution": "大學或學校名稱",
    "placeholder.qualification": "學位或資格（YYYY - YYYY）",
}
